# Generated by Django 4.1.13 on 2023-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contraseña', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='mail_paciente',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Mail del Paciente'),
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='nom_doctor',
            field=models.CharField(max_length=50, verbose_name='Nombre del Doctor'),
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='nom_paciente',
            field=models.CharField(max_length=50, verbose_name='Nombre del Paciente'),
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='rut_doctor',
            field=models.CharField(max_length=10, verbose_name='Rut del Doctor'),
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='rut_paciente',
            field=models.CharField(max_length=10, verbose_name='Rut del Paciente'),
        ),
    ]
