# Generated by Django 4.1.13 on 2023-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0002_usuario_alter_horamedica_mail_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='atributo',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('secretaria', 'Secretaria'), ('cajero', 'Cajero'), ('medico', 'Medico')], default='paciente', max_length=10),
        ),
    ]
